[tool.poetry]
name = "jolly"
version = "0.1.0"
description = "Import modules and files straight from URLs."
authors = ["GrandMoff100 <nlarsen23.student@gmail.com>", "FoxNerdSaysMoo <zceboys@gmail.com>"]
packages = [
    { include = "jolly" }
]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
flake8 = "^4.0.1"
black = "^21.12b0"
isort = "^5.10.1"

[tool.isort]
profile = "black"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
